"""Offline mock provider for tests."""

import json
from .llm_adapter import LLMAdapterBase


class MockLLMAdapter(LLMAdapterBase):
    adapter_name = "mock"
    model_name = "mock"

    def complete(self, prompt: str, context: dict | None = None) -> dict:
        payload = {
            "summary": "Structured reasoning proposal generated by mock provider.",
            "observations": ["context packet received"],
            "interpretations": [],
            "assumptions": [],
            "uncertainties": ["real provider not used in this test"],
            "evidence_refs": [],
            "candidate_steps": [],
            "risk_flags": [],
            "confidence": 0.5,
        }
        return {"ok": True, "raw_text": json.dumps(payload), "model_name": self.model_name, "adapter_name": self.adapter_name}
